# Generated by Django 4.0 on 2022-01-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_watering_plant_alter_watering_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watering',
            old_name='meal',
            new_name='tod',
        ),
    ]
