# Generated by Django 4.0 on 2022-01-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_fertilizer_alter_watering_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fertilizers',
            field=models.ManyToManyField(to='main_app.Fertilizer'),
        ),
    ]
